# Site settings
title: "victoria's 万事屋"
description: "victoria's 万事屋"
url: 'https://victoria14001.github.io/'
baseurl: ''
profilepic: '/images/beauty_girl.JPG'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'b99e675b6e.js'

author:
  name: 'Victoria 201114001'
  email: 461357639@@qq.com
  twitter_username: jessic_yang0603
#  facebook_username: joshgerdes
  github_username:  Victoria14001
  weibo_username: 2710898935
  zhihu_username: victoria14001
  stackoverflow_username: 8356851
  facebook_name: 100014098986256
  linkedin_username:  梦杰-杨-761025130
  meetup_name: victoria
  instagram_username: victoria_14001

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
