# Site settings
title: Victoria 201114001
description: '个人博客'
url: 'https://victoria14001.github.io/'
baseurl: ''
profilepic: '/images/beauty_girl.JPG'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Victoria 201114001'
  email: 461357639@@qq.com
  twitter_username: jessic_yang0603
#  facebook_username: joshgerdes
  github_username:  Victoria14001
  weibo_username: Victoria_Jmy
  zhihu_username: Victoria
#   linkedin_username:  thomas-zühlke-889182165
#   meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
